apiVersion: v1
kind: Pod
metadata:
  name: online-inference-ml-resources
  labels:
    app: online-inference-ml-resources
spec:
  containers:
    - image: imdxd/online_inference:latest
      name: online-inference-ml
      ports:
        - containerPort: 8090
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
